apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-configmap-rollouts

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-configmap-rollouts

    spec:
      containers:
      - name: kubernetes-configmap-rollouts
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: aabed/kube-configmap-updater
        imagePullPolicy: Always
